import React from 'react'
import Head from 'next/head'

const SEO = () => {
  const title = "A photo gallery that serves creators & collectors of art and photography generally."
  return (
    <Head>
      <title>ARSTY | {title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta property="og:title" content={`ARSTY | ${title}`} />
      <meta property="og:type" content="website" />
      <meta property="og:image" content="" />
      <meta property="og:url" content="https://www.colbyfayock.com" />

      <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default SEO
